"""R3 #28 row-12 external checks - generated CODEOWNERS, the three views,
the enforcement-evidence report, and the central generated-artifact manifest
(T20 #22 d6; T06 #8 d2/d3; spec 3 W7).

Generation is deterministic (identical sources and generator produce
identical bytes; no wall-clock timestamps in generated bytes), alias-only,
and format-aware: documentation formats embed the d6 envelope, the
control-format CODEOWNERS carries no envelope, and every artifact's
whole-file SHA-256 is bound in the manifest - which itself carries no
self-digest. The full generated set must pass this repository's own GEN
validation arms and the GOV-CODEOWNERS agreement check.
"""

import sys
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from validator import governance_generator as gen  # noqa: E402
from validator import runner  # noqa: E402

from tests.test_validator_governance_families import (  # noqa: E402
    GovTreeCase, PRINCIPAL, REVIEW_CLASS, ROUTING,
)
from tests.test_validator_access_families import FIXTURE  # noqa: E402

HANDLES = (
    "handles:\n"
    "  identity-platform: \"@a24577t\"\n"
)

REVISION = "b" * 40


class DictSources:
    """Synthetic source tree with fixed revisions (no git)."""

    def __init__(self, mapping, revisions=None):
        self.mapping = dict(mapping)
        self.revisions = revisions or {}

    def read(self, path):
        value = self.mapping.get(path)
        return value.encode("utf-8") if isinstance(value, str) else value

    def ls(self, prefix):
        return sorted(p for p in self.mapping if p.startswith(prefix))

    def revision(self, path):
        return self.revisions.get(path, REVISION)


def sources(with_fixture=True):
    mapping = {
        "governance/ownership/routing.yml": ROUTING,
        "governance/ownership/principals/identity-platform.yml": PRINCIPAL,
        "governance/ownership/review-classes/identity-platform.yml":
            REVIEW_CLASS,
        "governance/ownership/handles.yml": HANDLES,
        "access/identity-center/groups/lab-readers.yml":
            "key: lab-readers\nidentity_store_name: Lab Readers\n",
        "access/identity-center/permission-sets/read-only.yml":
            "key: read-only\ndescription: Read-only.\n"
            "session_duration: PT8H\nmanaged_policies:\n"
            "  - arn:aws:iam::aws:policy/ReadOnlyAccess\n",
        "access/identity-center/account-assignments/lab-workload-a/"
        "lab-readers--read-only.yml":
            "account: lab-workload-a\nprincipal:\n  type: GROUP\n"
            "  group: lab-readers\npermission_set: read-only\n",
    }
    if with_fixture:
        mapping["governance/inventory/lab-inventory-fixture.yml"] = FIXTURE
    return DictSources(mapping)


class Generation(unittest.TestCase):
    def test_the_complete_artifact_set(self) -> None:
        outputs = gen.generate(sources())
        self.assertEqual(
            [
                ".github/CODEOWNERS",
                "docs/generated/enforcement-evidence.md",
                "docs/generated/generated-artifacts.yml",
                "docs/generated/views/account.md",
                "docs/generated/views/principal.md",
                "docs/generated/views/requester.md",
            ],
            sorted(outputs),
        )

    def test_generation_is_byte_deterministic(self) -> None:
        self.assertEqual(gen.generate(sources()), gen.generate(sources()))

    def test_codeowners_derives_routing_then_delegation(self) -> None:
        text = gen.generate(sources())[".github/CODEOWNERS"].decode("utf-8")
        rules = [l for l in text.split("\n")
                 if l.strip() and not l.startswith("#")]
        self.assertEqual("/access/** @a24577t", rules[0])
        self.assertIn(
            "/access/identity-center/account-assignments/lab-workload-a/** "
            "@a24577t",
            rules,
        )
        self.assertFalse(text.startswith("---"))

    def test_codeowners_without_a_fixture_records_the_absence(self) -> None:
        text = gen.generate(sources(with_fixture=False))[
            ".github/CODEOWNERS"].decode("utf-8")
        self.assertIn("no committed inventory fixture", text)
        self.assertNotIn("account-assignments/lab-workload-a", text)

    def test_never_a_target_account_yields_no_delegation_rule(self) -> None:
        # lab-management carries intended_classification none (T16 #11 d7).
        text = gen.generate(sources())[".github/CODEOWNERS"].decode("utf-8")
        self.assertNotIn("lab-management", text)

    def test_envelopes_are_schema_ordered_without_self_digest(self) -> None:
        outputs = gen.generate(sources())
        view = outputs["docs/generated/views/requester.md"].decode("utf-8")
        self.assertTrue(view.startswith(
            "---\nauthority: generated\ndo_not_edit: true\ngenerator:\n"))
        self.assertIn("target:\n  path: docs/generated/views/requester.md",
                      view)
        header = view.split("---\n")[1]
        self.assertNotIn("sha256", header.split("sources")[0])

    def test_views_are_alias_only(self) -> None:
        outputs = gen.generate(sources())
        for path, blob in sorted(outputs.items()):
            text = blob.decode("utf-8")
            self.assertNotIn("111100000003", text, path)
            self.assertNotIn("d-0000000000", text, path)

    def test_deferred_alias_is_reported_deferred_in_views(self) -> None:
        mapping = sources()
        mapping.mapping[
            "access/identity-center/account-assignments/lab-requested/"
            "lab-readers--read-only.yml"
        ] = ("account: lab-requested\nprincipal:\n  type: GROUP\n"
             "  group: lab-readers\npermission_set: read-only\n")
        account_view = gen.generate(mapping)[
            "docs/generated/views/account.md"].decode("utf-8")
        self.assertIn("deferred", account_view)
        self.assertNotIn("invalid", account_view)

    def test_unresolvable_revision_aborts(self) -> None:
        bad = sources()
        bad.revision = lambda path: None
        with self.assertRaises(gen.GenerationError):
            gen.generate(bad)


class MaterializedTree(GovTreeCase):
    """The generated set, written into a governed tree, satisfies this
    repository's own GEN arms and the GOV-CODEOWNERS agreement check."""

    def materialize(self):
        outputs = gen.generate(sources())
        for path, blob in outputs.items():
            full = self.target / path
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_bytes(blob)
        return outputs

    def test_generated_set_passes_the_gen_arms(self) -> None:
        self.materialize()
        result = runner.run(
            "validation", self.target,
            runner.RunConfig(inventory_fixture=self.fixture),
        )
        self.assertEqual(
            [], [f.code for f in result if f.code.startswith("GEN-")]
        )

    def test_generated_codeowners_agrees_with_the_registry(self) -> None:
        outputs = self.materialize()
        result = runner.run(
            "generated-ci", self.target,
            runner.RunConfig(
                inventory_fixture=self.fixture,
                handle_mapping={"identity-platform": "@a24577t"},
                codeowners=outputs[".github/CODEOWNERS"].decode("utf-8"),
                regenerated=outputs,
            ),
        )
        self.assertEqual(
            [],
            [f.code for f in result
             if f.code in ("GOV-CODEOWNERS", "GEN-DRIFT")],
        )


if __name__ == "__main__":
    unittest.main()
