"""Generated governance artifacts (R3 #28 row 12; T20 #22 d6; T06 #8 d2/d3).

Produces, deterministically and only from committed governed sources, the
complete generated set: `.github/CODEOWNERS` (control format - manifest
metadata only, never an envelope), the three views (requester, account,
principal) and the enforcement-evidence report (documentation formats with
the embedded d6 envelope), and the central generated-artifact manifest at
its fixed path `docs/generated/generated-artifacts.yml` (whole-file SHA-256
per target; no self-digest - its integrity is deterministic regeneration
plus the CI comparison).

Derivation chain (T06 #8 d2): governed path -> required review class(es) ->
satisfying logical principal(s) -> the committed principal-to-GitHub-handle
mapping (`governance/ownership/handles.yml`, the implementation mapping
T06 defers under document 10; a strictest-set control surface) ->
CODEOWNERS. Views derive only from `access/**`, the committed inventory
fixture, and the effective-access derivation (T20 d6); while the repository
carries no committed fixture, delegation rules and lifecycle status derive
as explicitly `unresolved` - recorded, never a permissive fallback.

No wall-clock timestamp enters generated bytes; identical sources and
generator produce identical bytes (spec 8.2; GEN-DRIFT). Every public line
passes the T20 d3 identifier boundary before serialization.

Run: python -m validator.catalog-style entry - `python -m
validator.governance_generator [--check]` after the sources are committed
(source revisions are the exact commits that introduced the consumed
bytes; an unresolvable revision aborts, fail closed).
"""

import hashlib
import subprocess
import sys
from pathlib import Path

import yaml

from .effective_access import sanitize_public_text, _assert_public

GENERATOR_VERSION = "1"
GENERATOR_PATH = "src/validator/governance_generator.py"

MANIFEST_PATH = "docs/generated/generated-artifacts.yml"
CODEOWNERS_PATH = ".github/CODEOWNERS"
VIEW_PATHS = {
    "requester": "docs/generated/views/requester.md",
    "account": "docs/generated/views/account.md",
    "principal": "docs/generated/views/principal.md",
}
REPORT_PATH = "docs/generated/enforcement-evidence.md"

ROUTING_PATH = "governance/ownership/routing.yml"
HANDLES_PATH = "governance/ownership/handles.yml"
PRINCIPALS_PREFIX = "governance/ownership/principals/"
CLASSES_PREFIX = "governance/ownership/review-classes/"
FIXTURE_PATH = "governance/inventory/lab-inventory-fixture.yml"
ACCESS_PREFIX = "access/identity-center/"

RESOURCE_NAME_PREFIX = "ialab-"


class GenerationError(Exception):
    """A source the deterministic generation contract cannot consume."""


def _load_yaml(sources, path):
    blob = sources.read(path)
    if blob is None:
        return None
    try:
        return yaml.safe_load(blob.decode("utf-8"))
    except Exception as exc:
        raise GenerationError(f"{path}: unparseable source "
                              f"({exc.__class__.__name__})")


def _collect(sources):
    """Every parsed source the generated set derives from."""
    data = {
        "routing": _load_yaml(sources, ROUTING_PATH),
        "handles": (_load_yaml(sources, HANDLES_PATH) or {}).get("handles"),
        "classes": {},
        "principals": {},
        "groups": {},
        "permission_sets": {},
        "assignments": [],
        "fixture": _load_yaml(sources, FIXTURE_PATH),
        "paths": [],
    }
    if not isinstance(data["routing"], dict):
        raise GenerationError(f"{ROUTING_PATH}: missing or not a mapping")
    if not isinstance(data["handles"], dict):
        raise GenerationError(f"{HANDLES_PATH}: missing handles mapping")
    data["paths"].extend([ROUTING_PATH, HANDLES_PATH])
    for path in sources.ls(CLASSES_PREFIX):
        body = _load_yaml(sources, path)
        if isinstance(body, dict) and isinstance(body.get("key"), str):
            data["classes"][body["key"]] = body
            data["paths"].append(path)
    for path in sources.ls(PRINCIPALS_PREFIX):
        body = _load_yaml(sources, path)
        if isinstance(body, dict) and isinstance(body.get("key"), str):
            data["principals"][body["key"]] = body
            data["paths"].append(path)
    for path in sources.ls(ACCESS_PREFIX + "groups/"):
        body = _load_yaml(sources, path)
        if isinstance(body, dict) and isinstance(body.get("key"), str):
            data["groups"][body["key"]] = body
            data["paths"].append(path)
    for path in sources.ls(ACCESS_PREFIX + "permission-sets/"):
        body = _load_yaml(sources, path)
        if isinstance(body, dict) and isinstance(body.get("key"), str):
            data["permission_sets"][body["key"]] = body
            data["paths"].append(path)
    for path in sources.ls(ACCESS_PREFIX + "account-assignments/"):
        body = _load_yaml(sources, path)
        if isinstance(body, dict):
            data["assignments"].append((path, body))
            data["paths"].append(path)
    if data["fixture"] is not None:
        data["paths"].append(FIXTURE_PATH)
    return data


def _handles_for(data, class_keys):
    out = set()
    for cls in class_keys:
        body = data["classes"].get(cls)
        if not isinstance(body, dict):
            continue
        for principal in body.get("satisfied_by") or ():
            handle = data["handles"].get(str(principal))
            if isinstance(handle, str) and handle:
                out.add(handle)
    return sorted(out)


def _fixture_entries(data):
    fixture = data["fixture"]
    if not isinstance(fixture, dict):
        return None
    table = {}
    for entry in fixture.get("accounts") or ():
        if isinstance(entry, dict) and isinstance(entry.get("alias"), str):
            table.setdefault(entry["alias"], entry)
    return table


def _codeowners(data):
    lines = [
        "# Generated CODEOWNERS - do not edit; regeneration is the only",
        f"# change path. Metadata: {MANIFEST_PATH} (T20 #22 d6).",
    ]
    routes = data["routing"].get("routes")
    if not isinstance(routes, list):
        raise GenerationError(f"{ROUTING_PATH}: missing routes list")
    entries = _fixture_entries(data)
    delegation = []
    for route in routes:
        if not isinstance(route, dict) or not isinstance(route.get("path"), str):
            raise GenerationError(f"{ROUTING_PATH}: malformed route record")
        declared = route.get("review_classes")
        if isinstance(declared, list) and declared:
            handles = _handles_for(data, [str(c) for c in declared])
            if not handles:
                raise GenerationError(
                    f"{ROUTING_PATH}: route {route['path']} resolves to no "
                    "handle - fail closed, never an ownerless rule")
            lines.append(f"/{route['path']} " + " ".join(handles))
        elif route.get("resolution") == "account-delegation":
            delegation.append(route)
    if delegation:
        if entries is None:
            lines.append(
                "# account-delegation rules derive from the committed "
                "inventory fixture;")
            lines.append(
                "# no committed inventory fixture exists at generation time "
                "- unresolved,")
            lines.append(
                "# never a permissive fallback (T06 #8 d3; T10 #15 d5).")
        else:
            for alias in sorted(entries):
                classification = entries[alias].get("intended_classification")
                if classification and classification != "none" \
                        and classification in data["classes"]:
                    handles = _handles_for(data, [classification])
                    if handles:
                        lines.append(
                            f"/access/identity-center/account-assignments/"
                            f"{alias}/** " + " ".join(handles))
    return "\n".join(lines) + "\n"


def _lifecycle(alias, entries):
    if entries is None:
        return ("unresolved - no committed inventory fixture (deferral "
                "derives from the fixture)")
    entry = entries.get(alias)
    if entry is None:
        return "unresolved - alias absent from the committed fixture"
    if entry.get("status") == "requested":
        return "deferred - reported deferred, never rejected (RD-08)"
    return "standing - until changed by governed PR"


def _assignment_rows(data):
    entries = _fixture_entries(data)
    rows = []
    for path, body in sorted(data["assignments"]):
        principal = body.get("principal")
        group = principal.get("group") if isinstance(principal, dict) else None
        alias = body.get("account")
        ps_key = body.get("permission_set")
        if not all(isinstance(v, str) for v in (group, alias, ps_key)):
            continue
        ps = data["permission_sets"].get(ps_key, {})
        rows.append({
            "group": group,
            "alias": alias,
            "permission_set": ps_key,
            "duration": str(ps.get("session_duration", "-")),
            "portal": RESOURCE_NAME_PREFIX + ps_key,
            "lifecycle": _lifecycle(alias, entries),
        })
    return rows


def _requester_view(data):
    rows = _assignment_rows(data)
    out = ["# Requester view", "",
           "What each workforce group receives, derived from the governed",
           "requester surface. Non-authoritative rendering.", ""]
    by_group = {}
    for row in rows:
        by_group.setdefault(row["group"], []).append(row)
    for group in sorted(by_group):
        out.append(f"## {group}")
        out.append("")
        for row in by_group[group]:
            out.append(
                f"- {row['alias']}: {row['permission_set']} "
                f"(session {row['duration']}; portal {row['portal']}) - "
                f"{row['lifecycle']}")
        out.append("")
    if not by_group:
        out.extend(["no assignments", ""])
    return "\n".join(out)


def _account_view(data):
    rows = _assignment_rows(data)
    out = ["# Account view", "",
           "Effective access per stable account alias. Aliases only, ever.",
           ""]
    by_alias = {}
    for row in rows:
        by_alias.setdefault(row["alias"], []).append(row)
    for alias in sorted(by_alias):
        out.append(f"## {alias}")
        out.append("")
        for row in by_alias[alias]:
            out.append(
                f"- {row['group']} -> {row['permission_set']} "
                f"(portal {row['portal']}) - {row['lifecycle']}")
        out.append("")
    if not by_alias:
        out.extend(["no assignments", ""])
    return "\n".join(out)


def _principal_view(data):
    rows = _assignment_rows(data)
    counts = {}
    for row in rows:
        counts[row["group"]] = counts.get(row["group"], 0) + 1
    out = ["# Principal view", "",
           "Workforce-group principals of the governed surface. Groups are",
           "references - resolved, never created or managed (ADR-0007).", ""]
    for key in sorted(data["groups"]):
        body = data["groups"][key]
        name = body.get("identity_store_name", "-")
        out.append(f"## {key}")
        out.append("")
        out.append(f"- identity_store_name: {name}")
        out.append(f"- assignments: {counts.get(key, 0)}")
        out.append("- lifecycle: referenced, never managed (ADR-0007)")
        out.append("")
    if not data["groups"]:
        out.extend(["no group references", ""])
    return "\n".join(out)


def _enforcement_report(data):
    out = ["# Enforcement evidence", "",
           "Per-class enforcement status. Status is always derived, never",
           "authored (T06 #8 d2/d3).", ""]
    for key in sorted(data["classes"]):
        body = data["classes"][key]
        satisfied = ", ".join(
            str(p) for p in body.get("satisfied_by") or ()) or "-"
        out.append(f"## {key}")
        out.append("")
        out.append(f"- satisfied by: {satisfied}")
        out.append(
            "- derived status: unenforced - recorded T15 #10 d15 procedural "
            "interval; server-side control activation is item 14a (R6 #31), "
            "separately authorized; never a permissive fallback")
        out.append("")
    if not data["classes"]:
        out.extend(["no review classes", ""])
    return "\n".join(out)


def _envelope(sources, target_path, source_paths):
    lines = ["---", "authority: generated", "do_not_edit: true",
             "generator:", f"  path: {GENERATOR_PATH}",
             f"  version: \"{GENERATOR_VERSION}\"", "sources:"]
    for path in sorted(source_paths):
        revision = sources.revision(path)
        if not isinstance(revision, str) or len(revision) != 40:
            raise GenerationError(
                f"{path}: source revision unresolvable - generate only "
                "from committed sources (fail closed)")
        lines.append(f"  - path: {path}")
        lines.append(f"    revision: \"{revision}\"")
    lines.extend(["target:", f"  path: {target_path}", "---", ""])
    return "\n".join(lines) + "\n"


def _public(text):
    sanitized = "\n".join(
        sanitize_public_text(line) for line in text.split("\n"))
    _assert_public(sanitized)
    return sanitized.encode("utf-8")


def generate(sources):
    """-> {repository-relative path: exact bytes} for the generated set."""
    data = _collect(sources)
    governance_paths = [ROUTING_PATH, HANDLES_PATH] + [
        p for p in data["paths"]
        if p.startswith((CLASSES_PREFIX, PRINCIPALS_PREFIX))
    ]
    access_paths = [p for p in data["paths"]
                    if p.startswith(ACCESS_PREFIX)]
    fixture_paths = ([FIXTURE_PATH] if data["fixture"] is not None else [])

    outputs = {
        CODEOWNERS_PATH: _public(_codeowners(data)),
        VIEW_PATHS["requester"]: (
            _envelope(sources, VIEW_PATHS["requester"],
                      access_paths + fixture_paths).encode("utf-8")
            + _public(_requester_view(data))),
        VIEW_PATHS["account"]: (
            _envelope(sources, VIEW_PATHS["account"],
                      access_paths + fixture_paths).encode("utf-8")
            + _public(_account_view(data))),
        VIEW_PATHS["principal"]: (
            _envelope(sources, VIEW_PATHS["principal"],
                      access_paths + fixture_paths).encode("utf-8")
            + _public(_principal_view(data))),
        REPORT_PATH: (
            _envelope(sources, REPORT_PATH,
                      governance_paths).encode("utf-8")
            + _public(_enforcement_report(data))),
    }

    entry_sources = {
        CODEOWNERS_PATH: governance_paths + fixture_paths,
        VIEW_PATHS["requester"]: access_paths + fixture_paths,
        VIEW_PATHS["account"]: access_paths + fixture_paths,
        VIEW_PATHS["principal"]: access_paths + fixture_paths,
        REPORT_PATH: governance_paths,
    }
    manifest = []
    for target in sorted(outputs):
        digest = hashlib.sha256(outputs[target]).hexdigest()
        manifest.append(f"- target:\n    path: {target}\n"
                        f"    sha256: \"{digest}\"")
        manifest.append(f"  generator:\n    path: {GENERATOR_PATH}\n"
                        f"    version: \"{GENERATOR_VERSION}\"")
        manifest.append("  sources:")
        for path in sorted(set(entry_sources[target])):
            revision = sources.revision(path)
            if not isinstance(revision, str) or len(revision) != 40:
                raise GenerationError(
                    f"{path}: source revision unresolvable (fail closed)")
            manifest.append(f"    - path: {path}")
            manifest.append(f"      revision: \"{revision}\"")
    outputs[MANIFEST_PATH] = ("\n".join(manifest) + "\n").encode("utf-8")
    return outputs


class GitSources:
    """Committed-byte sources (byte-identity amendment): blobs at HEAD,
    revisions from the commit that last touched each path."""

    def __init__(self, root=None):
        self.root = Path(root) if root else Path(__file__).resolve().parents[2]

    def _git(self, *args):
        return subprocess.run(["git", *args], cwd=self.root,
                              capture_output=True, check=True).stdout

    def read(self, path):
        try:
            return self._git("cat-file", "blob", f"HEAD:{path}")
        except subprocess.CalledProcessError:
            return None

    def ls(self, prefix):
        out = self._git("ls-tree", "-r", "--name-only", "HEAD", prefix)
        return sorted(l for l in out.decode("utf-8").split("\n") if l)

    def revision(self, path):
        out = self._git("log", "-1", "--format=%H", "HEAD", "--", path)
        value = out.decode("utf-8").strip()
        return value or None


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    check_only = "--check" in argv
    sources = GitSources()
    outputs = generate(sources)
    drift = []
    for rel, blob in sorted(outputs.items()):
        path = sources.root / rel
        if not path.is_file() or path.read_bytes() != blob:
            drift.append(path)
    if check_only:
        if drift:
            for path in drift:
                print(f"DRIFT: {path}")
            return 1
        print("regeneration identical (deterministic)")
        return 0
    for rel, blob in sorted(outputs.items()):
        path = sources.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(blob)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
