"""The validator run seam (R2 #27 row 3).

One public entry: run(stage, target, config) -> canonically ordered findings.
Stages are the closed T14 #19 d3 vocabulary. The hermetic boundary is
enforced structurally: the validation stage refuses a plan context and holds
no clock, snapshot, evidence, or AWS input (T22 #21 d4; T09 #12 d15; T15 #10
d6); plan and apply require their explicit plan-context input - this validator
core never contacts AWS itself, the pipeline supplies the stage's facts.
Locators derive from canonical traversal of the canonically ordered input
domain: files in byte-lexicographic path order, document order within a file
(T14 #19 C14) - never from filesystem enumeration order.
"""

from pathlib import Path

from . import catalogue, findings, leak


class RunConfig:
    """Explicit run inputs - everything the checks may consume.

    resource_name_prefix: the deployment-scope prefix (T15 #10 d8 selects
    ialab-); part of run configuration so the prefix-budget rule is checkable.
    inventory_fixture: path to the committed labeled lab inventory fixture
    consumed by validation-stage INV checks (T09 #12 d3).
    plan_context: the plan/apply-stage input document (snapshot envelope,
    controlled clock, live facts, evidence stubs) - prohibited at validation.
    handle_mapping / codeowners: generated-ci-stage inputs (GOV-CODEOWNERS).
    """

    def __init__(self, resource_name_prefix="ialab-", inventory_fixture=None,
                 plan_context=None, handle_mapping=None, codeowners=None,
                 catalog_dir=None, catalog_reference=None, changed_paths=None,
                 regenerated=None):
        self.resource_name_prefix = resource_name_prefix
        self.inventory_fixture = inventory_fixture
        self.plan_context = plan_context
        self.handle_mapping = handle_mapping
        self.codeowners = codeowners
        # changed_paths: the PR's changed-file set for T20 #22 d2
        # classification (CLS validation arms; the R4 CI wiring supplies it).
        self.changed_paths = changed_paths
        # regenerated: {repo-relative path: freshly regenerated bytes} for
        # the generated-ci GEN-DRIFT comparison (pipeline-supplied).
        self.regenerated = regenerated
        # ADM rules 2/4 data (T14 #19 d5; spec 7.4): default to the
        # repository-controlled catalogs and the validator's committed
        # catalog reference; overridable for specimen runs.
        repo_root = Path(__file__).resolve().parent.parent.parent
        self.catalog_dir = Path(
            catalog_dir if catalog_dir is not None
            else repo_root / "governance" / "catalogs"
        )
        self.catalog_reference = Path(
            catalog_reference if catalog_reference is not None
            else Path(__file__).resolve().parent / "catalog_reference.json"
        )


class Context:
    """Per-run state handed to checks."""

    def __init__(self, stage, target, config):
        self.stage = stage
        self.target = Path(target)
        self.config = config
        self.findings = []
        self._cache = {}

    def emit(self, code, file_path=None, field_path=None, value=None,
             message=""):
        entry = catalogue.CATALOGUE[code]
        self.findings.append(
            findings.Finding(
                code=code,
                stage=self.stage,
                file_path=file_path,
                field_path=field_path,
                rule_ids=entry.rule_ids,
                value=value,
                message=message,
            )
        )

    def files(self):
        """Every regular file under the target, repo-relative POSIX paths,
        byte-lexicographic order (C14 canonical traversal)."""
        key = "files"
        if key not in self._cache:
            paths = []
            for p in self.target.rglob("*"):
                if not p.is_file():
                    continue
                rel = p.relative_to(self.target).as_posix()
                # Git object storage and interpreter caches are not governed
                # content.
                if rel.startswith(".git/") or "__pycache__" in rel:
                    continue
                paths.append(rel)
            self._cache[key] = sorted(paths)
        return self._cache[key]

    def read_bytes(self, rel):
        return (self.target / rel).read_bytes()


# Check registry: (name, frozenset of stages, callable(Context) -> None).
# Populated by the family modules; the row-3 core registers the leak rule.
CHECKS = []


def register(name, stages, fn):
    CHECKS.append((name, frozenset(stages), fn))


def run(stage, target, config=None):
    """Run every registered check for the stage; return canonical findings."""
    config = config or RunConfig()
    if stage not in catalogue.STAGES:
        raise findings.ContractViolation(
            f"stage {stage!r} outside the closed stage vocabulary"
        )
    if stage == "validation" and config.plan_context is not None:
        raise findings.ContractViolation(
            "hermetic boundary: the validation stage holds no clock and reads "
            "no snapshot, evidence, or plan context (T22 #21 d4)"
        )
    if stage in ("plan", "apply") and config.plan_context is None:
        raise findings.ContractViolation(
            f"the {stage} stage requires its explicit plan-context input"
        )
    ctx = Context(stage, target, config)
    for _name, stages, fn in CHECKS:
        if stage in stages:
            fn(ctx)
    return findings.canonical(ctx.findings)


register("public-leak", ("validation", "generated-ci"), leak.check_tree)

from . import checks_access  # noqa: E402  (registration order is load order)
from . import checks_doc  # noqa: E402
from . import checks_governance  # noqa: E402

register("out-of-slice", ("validation",), checks_access.check_out_of_slice)
register("groups", ("validation",), checks_access.check_groups)
register("permission-sets", ("validation",), checks_access.check_permission_sets)
register("assignments", ("validation",), checks_access.check_assignments)
register("instance", ("validation",), checks_access.check_instance)
register("fixture", ("validation",), checks_governance.check_fixture)
register("registry", ("validation",), checks_governance.check_registry)
register("routing", ("validation",), checks_governance.check_routing)
register("declarations", ("validation",), checks_governance.check_declarations)
register("codeowners", ("generated-ci",), checks_governance.check_codeowners)
register("docs", ("validation",), checks_doc.check_docs)

from . import checks_adm  # noqa: E402
from . import checks_plan  # noqa: E402

register("adm", ("validation",), checks_adm.check_adm)
register("plan-battery", ("plan", "apply"), checks_plan.check_plan_stage)

from . import checks_ado  # noqa: E402
from . import checks_cls  # noqa: E402
from . import checks_gen  # noqa: E402

register("ado", ("validation",), checks_ado.check_ado)
register("cls-paths", ("validation",), checks_cls.check_paths_validation)
register("cls-plan", ("plan", "apply"), checks_cls.check_plan_classification)
register("generated", ("validation", "generated-ci"),
         checks_gen.check_generated)
register("gen-drift", ("generated-ci",), checks_gen.check_drift)
